version: "3.1"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  
  springrest:
    image: springrest
    environment:
      - KAFKA_IP_PORT=kafka:29092
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    build:
      context: "./springrest/"
      dockerfile: Dockerfile
  
  subscribe:
    image: subscribe
    environment:
      - KAFKA_IP_PORT=kafka:29092
    depends_on:
      - kafka
    ports:
      - "8082:8082"
    build:
      context: "./subscribe/"
      dockerfile: Dockerfile
  
  notifications:
    image: notifications
    environment:
      - KAFKA_IP_PORT=kafka:29092
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    build:
      context: "./notifications/"
      dockerfile: Dockerfile

networks:
  kafka_network:
    name: kafka_docker_example_net
    
  